name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: swift build -v
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer


